// HO 180: PER-TOPIC colors (was 8 group colors shared across 24 topics). Each
// topic gets its own hue so every bubble is visually distinct; the bubble hover
// popover (full category name) is the source of truth when two near-collide.
// Generated by a systematic HSL scale — golden-angle hue stepping (good scatter
// so pack-adjacent bubbles differ), S 68%, L alternating 62/55% for legibility
// on the #050709 dark bg, with the amber/yellow hue band (~35-65°) SKIPPED so no
// fill fights the `--accent-amber-bright` selection stroke. `other` stays neutral
// gray. Static so a given topic is always the same color (not index-derived).
export const TOPIC_COLORS: Record<string, string> = {
  healthcare: "#e05c8e",
  immigration: "#4bda3e",
  taxes: "#785ce0",
  defense: "#da8c3e",
  energy: "#5ce0c5",
  environment: "#da3ecd",
  education: "#aee05c",
  labor: "#3e72da",
  technology: "#e05c62",
  civil_rights: "#3eda65",
  criminal_justice: "#a45ce0",
  agriculture: "#3ec7da",
  trade: "#e05ca9",
  housing: "#6bda3e",
  transportation: "#5c5ce0",
  foreign_policy: "#da6c3e",
  veterans: "#5ce0a9",
  elections: "#c73eda",
  budget: "#cae05c",
  financial_services: "#3e92da",
  government_operations: "#e05c7d",
  consumer_protection: "#3eda45",
  social_security: "#895ce0",
  other: "#6b7280",
};

export const TOPIC_LABELS: Record<string, string> = {
  healthcare: "HLTH",
  immigration: "IMM",
  taxes: "TAX",
  defense: "DEF",
  energy: "ENRG",
  environment: "ENV",
  education: "EDU",
  labor: "LAB",
  technology: "TECH",
  civil_rights: "CIV",
  criminal_justice: "CRIM",
  agriculture: "AGR",
  trade: "TRD",
  housing: "HSG",
  transportation: "TRNS",
  foreign_policy: "FRGN",
  veterans: "VET",
  elections: "ELEC",
  budget: "BDGT",
  financial_services: "FIN",
  government_operations: "GOV",
  consumer_protection: "CONS",
  social_security: "SS",
  other: "OTHR",
};

export const TOPIC_FULL_LABELS: Record<string, string> = {
  healthcare: "Healthcare",
  immigration: "Immigration",
  taxes: "Taxes",
  defense: "Defense",
  energy: "Energy",
  environment: "Environment",
  education: "Education",
  labor: "Labor",
  technology: "Technology",
  civil_rights: "Civil rights",
  criminal_justice: "Criminal justice",
  agriculture: "Agriculture",
  trade: "Trade",
  housing: "Housing",
  transportation: "Transportation",
  foreign_policy: "Foreign policy",
  veterans: "Veterans",
  elections: "Elections",
  budget: "Budget",
  financial_services: "Financial services",
  government_operations: "Government operations",
  consumer_protection: "Consumer protection",
  social_security: "Social security",
  other: "Other",
};

export function topicColor(topic: string): string {
  return TOPIC_COLORS[topic] ?? TOPIC_COLORS.other!;
}

export function topicLabel(topic: string): string {
  return TOPIC_LABELS[topic] ?? topic.toUpperCase();
}

export function topicFullLabel(topic: string): string {
  return (
    TOPIC_FULL_LABELS[topic] ??
    topic.replace(/_/g, " ").replace(/^./, (c) => c.toUpperCase())
  );
}
